// Generated by scripts/design-tokens.py from docs/DESIGN.md. Don't edit: change DESIGN.md and run
// `make design-tokens`.
import AppKit
import SwiftUI

enum DesignTokens {
    /// Light and dark values switch with the window's appearance.
    enum Palette {
        static let bg = dynamic(light: 0xF3F3F5, dark: 0x1B1B1F)
        static let surface = dynamic(light: 0xFFFFFF, dark: 0x26262B)
        static let sunken = dynamic(light: 0xEAEAED, dark: 0x151518)
        static let border = dynamic(light: 0xDCDCE1, dark: 0x37373E)
        static let text = dynamic(light: 0x1F1F23, dark: 0xF2F2F4)
        static let text2 = dynamic(light: 0x5E5E66, dark: 0xA8A8B0)
        static let text3 = dynamic(light: 0x6F6F77, dark: 0x8E8E96)
        static let accent = dynamic(light: 0xFFD84D, dark: 0xF7C83A)
        static let accentPress = dynamic(light: 0xF7C83A, dark: 0xE9B92C)
        static let onAccent = dynamic(light: 0x2A2320, dark: 0x2A2320)
        static let accentSubtle = dynamic(light: 0xFFF5CC, dark: 0x3A3322)
        static let link = dynamic(light: 0x1F1F23, dark: 0xFFD84D)
        static let focus = dynamic(light: 0x2A2320, dark: 0xFFD84D)
        static let success = dynamic(light: 0x1A7340, dark: 0x6FD39A)
        static let successBg = dynamic(light: 0xE6F4EA, dark: 0x17301F)
        static let warning = dynamic(light: 0x9A4A0B, dark: 0xF4B070)
        static let warningBg = dynamic(light: 0xFDF1E4, dark: 0x3A2818)
        static let danger = dynamic(light: 0xB42318, dark: 0xFF8A80)
        static let dangerBg = dynamic(light: 0xFDEDEC, dark: 0x3D1E1D)
        static let dangerFill = dynamic(light: 0xC62828, dark: 0xE5484D)
        static let onDanger = dynamic(light: 0xFFFFFF, dark: 0xFFFFFF)
    }

    /// App font sizes in points.
    enum FontSize {
        static let micro: CGFloat = 10
        static let caption: CGFloat = 11
        static let footnote: CGFloat = 12
        static let body: CGFloat = 13
        static let callout: CGFloat = 14
        static let headline: CGFloat = 16
        static let title3: CGFloat = 18
        static let title: CGFloat = 22
        static let display: CGFloat = 28
    }

    enum Radius {
        static let sm: CGFloat = 6
        static let control: CGFloat = 10
        static let card: CGFloat = 12
        static let panel: CGFloat = 16
        static let pill: CGFloat = 999
    }

    enum Spacing {
        static let half: CGFloat = 2
        static let x1: CGFloat = 4
        static let x2: CGFloat = 8
        static let x3: CGFloat = 12
        static let x4: CGFloat = 16
        static let x5: CGFloat = 20
        static let x6: CGFloat = 24
        static let x8: CGFloat = 32
        static let x12: CGFloat = 48
        static let x16: CGFloat = 64
    }

    private static func dynamic(light: UInt32, dark: UInt32) -> Color {
        Color(nsColor: NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.darkAqua, .vibrantDark, .aqua, .vibrantLight])
            let hex = (isDark == .darkAqua || isDark == .vibrantDark) ? dark : light
            return NSColor(
                srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,
                blue: CGFloat(hex & 0xFF) / 255, alpha: 1)
        })
    }
}
