import AppKit
import SwiftUI

/// App icons are named by their SF Symbol name everywhere. The ones listed in PhosphorIcons (generated by
/// scripts/phosphor-symbols.py) draw as Yap's Phosphor symbols; the rest stay SF Symbols. Both are symbols, so
/// they size with the font and take foregroundStyle the same way.
extension Image {
    init(yapIcon systemName: String) {
        if let phosphor = PhosphorIcons.bySystemName[systemName] {
            self.init(phosphor)
        } else {
            self.init(systemName: systemName)
        }
    }

    /// The duotone tint layer of a Phosphor icon (`ph.<name>.duo`), for a selected sidebar item; nil when the icon
    /// has none.
    static func yapIconTint(_ systemName: String) -> Image? {
        guard let phosphor = PhosphorIcons.bySystemName[systemName],
            NSImage(named: phosphor + ".duo") != nil
        else { return nil }
        return Image(phosphor + ".duo")
    }
}

extension Label where Title == Text, Icon == Image {
    init(_ titleKey: LocalizedStringKey, yapIcon: String) {
        self.init { Text(titleKey) } icon: { Image(yapIcon: yapIcon) }
    }

    @_disfavoredOverload
    init<S: StringProtocol>(_ title: S, yapIcon: String) {
        self.init { Text(title) } icon: { Image(yapIcon: yapIcon) }
    }
}

#if DEBUG
    enum YapIconCheck {
        /// Every table entry resolves to a symbol in the asset catalog.
        static func selfCheck() {
            for (systemName, phosphor) in PhosphorIcons.bySystemName {
                assert(NSImage(named: phosphor) != nil, "missing Phosphor symbol \(phosphor) for \(systemName)")
            }
        }
    }
#endif
