import AppKit
import SwiftUI

struct ClipboardManager {
    static let pasteSessionType = NSPasteboard.PasteboardType("com.VoiceInk.PasteSession")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    enum ClipboardError: Error {
        case copyFailed
        case accessDenied
    }

    /// Writes all types in one item, so a clipboard-history app never sees the text before the
    /// transient markers that tell it to skip (and not chime on) this copy.
    static func setClipboard(
        _ text: String, transient: Bool = false, sessionID: String? = nil, on pasteboard: NSPasteboard = .general
    ) -> Bool {
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            item.setString(bundleIdentifier, forType: sourceType)
        }
        if transient {
            markTransient(item)
        }
        if let sessionID {
            item.setString(sessionID, forType: pasteSessionType)
        }

        pasteboard.clearContents()
        return pasteboard.writeObjects([item]) && pasteboard.string(forType: .string) == text
    }

    /// Puts back what the user had before a paste. Marked transient too: the history app already
    /// recorded it when the user copied it, and recording it again duplicates the entry (upstream #933).
    static func restoreClipboard(_ items: [NSPasteboardItem], on pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        items.forEach(markTransient)
        pasteboard.writeObjects(items)
    }

    private static func markTransient(_ item: NSPasteboardItem) {
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
    }

    #if DEBUG
        static func selfCheck() {
            let pasteboard = NSPasteboard(name: NSPasteboard.Name("yap.selfcheck.\(UUID().uuidString)"))
            defer { pasteboard.releaseGlobally() }
            assert(setClipboard("hello", transient: true, sessionID: "s1", on: pasteboard))
            let types = pasteboard.pasteboardItems?.first?.types ?? []
            assert(pasteboard.pasteboardItems?.count == 1)
            assert([.string, transientType, autoGeneratedType, pasteSessionType].allSatisfy(types.contains))
            assert(pasteboard.string(forType: pasteSessionType) == "s1")

            let saved = NSPasteboardItem()
            saved.setString("user text", forType: .string)
            restoreClipboard([saved], on: pasteboard)
            assert(pasteboard.string(forType: .string) == "user text")
            assert(pasteboard.pasteboardItems?.first?.types.contains(transientType) == true)
            assert(pasteboard.string(forType: pasteSessionType) == nil)
        }
    #endif

    static func copyToClipboard(_ text: String) -> Bool {
        return setClipboard(text, transient: false)
    }

    static func getClipboardContent() -> String? {
        return NSPasteboard.general.string(forType: .string)
    }
}

struct ClipboardMessageModifier: ViewModifier {
    @Binding var message: String

    func body(content: Content) -> some View {
        content
            .overlay(
                Group {
                    if !message.isEmpty {
                        Text(message)
                            .font(AppTheme.font(.caption))
                            .foregroundColor(AppTheme.Status.positive)
                            .padding(.horizontal, AppTheme.Spacing.x2)
                            .padding(.vertical, AppTheme.Spacing.x1)
                            .background(AppTheme.Status.positive.opacity(0.10))
                            .cornerRadius(AppTheme.Radius.small)
                            .transition(.opacity)
                            .animation(.easeInOut, value: message)
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topTrailing)
                .padding()
            )
    }
}

extension View {
    func clipboardMessage(_ message: Binding<String>) -> some View {
        self.modifier(ClipboardMessageModifier(message: message))
    }
}
