#!/usr/bin/env python3
"""Generates the app's and the web's design tokens from the `tokens` block in docs/DESIGN.md, and checks that
nothing bypasses them.

  scripts/design-tokens.py          write DesignTokens.generated.swift and design/web/tokens.css
  scripts/design-tokens.py --check  fail if those files are stale, or if app code / email templates hard-code
                                    a color, font size, corner radius or spacing value
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESIGN = os.path.join(ROOT, "docs/DESIGN.md")
SWIFT_OUT = os.path.join(ROOT, "VoiceInk/DesignSystem/Theme/DesignTokens.generated.swift")
CSS_OUT = os.path.join(ROOT, "design/web/tokens.css")
APP_DIR = os.path.join(ROOT, "VoiceInk")
THEME_DIR = os.path.join(APP_DIR, "DesignSystem/Theme")
WEB_DIR = os.path.join(ROOT, "design/web")

FONT_STACK = ('-apple-system, BlinkMacSystemFont, "SF Pro Text", "PingFang SC", "Hiragino Sans GB", '
              '"Helvetica Neue", sans-serif')
MONO_STACK = 'ui-monospace, "SF Mono", SFMono-Regular, Menlo, monospace'


def parse():
    text = open(DESIGN, encoding="utf-8").read()
    block = re.search(r"```tokens\n(.*?)```", text, re.S).group(1)
    tokens = {"color": [], "font": [], "radius": [], "space": []}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, *values = line.split()
        group, key = name.split(".", 1)
        if group == "color":
            tokens[group].append((key, values[0].upper(), values[1].upper()))
        elif group == "font":
            tokens[group].append((key, int(values[0]), int(values[1])))
        else:
            tokens[group].append((key, int(values[0])))
    return tokens


def camel(key):
    head, *rest = re.split(r"[-.]", key)
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def swift_space_name(key):
    return "half" if key == "half" else f"x{key}"


def swift(tokens):
    out = [
        "// Generated by scripts/design-tokens.py from docs/DESIGN.md. Don't edit: change DESIGN.md and run",
        "// `make design-tokens`.",
        "import AppKit",
        "import SwiftUI",
        "",
        "enum DesignTokens {",
        "    /// Light and dark values switch with the window's appearance.",
        "    enum Palette {",
    ]
    for key, light, dark in tokens["color"]:
        out.append(f"        static let {camel(key)} = dynamic(light: 0x{light[1:]}, dark: 0x{dark[1:]})")
    out += ["    }", "", "    /// App font sizes in points.", "    enum FontSize {"]
    for key, app, _web in tokens["font"]:
        out.append(f"        static let {camel(key)}: CGFloat = {app}")
    out += ["    }", "", "    enum Radius {"]
    for key, value in tokens["radius"]:
        out.append(f"        static let {camel(key)}: CGFloat = {value}")
    out += ["    }", "", "    enum Spacing {"]
    for key, value in tokens["space"]:
        out.append(f"        static let {swift_space_name(key)}: CGFloat = {value}")
    out += [
        "    }",
        "",
        "    private static func dynamic(light: UInt32, dark: UInt32) -> Color {",
        "        Color(nsColor: NSColor(name: nil) { appearance in",
        "            let isDark = appearance.bestMatch(from: [.darkAqua, .vibrantDark, .aqua, .vibrantLight])",
        "            let hex = (isDark == .darkAqua || isDark == .vibrantDark) ? dark : light",
        "            return NSColor(",
        "                srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,",
        "                blue: CGFloat(hex & 0xFF) / 255, alpha: 1)",
        "        })",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def css(tokens):
    def palette(index):
        return "\n".join(f"  --{key}: {values[index]};" for key, *values in tokens["color"])

    fonts = "\n".join(f"  --font-{key}: {web}px;" for key, _app, web in tokens["font"])
    radii = "\n".join(f"  --radius-{key}: {value}px;" for key, value in tokens["radius"])
    spaces = "\n".join(f"  --space-{key}: {value}px;" for key, value in tokens["space"])
    return f"""/* Generated by scripts/design-tokens.py from docs/DESIGN.md. Don't edit: change DESIGN.md and run
   `make design-tokens`. Light by default, dark with the system (prefers-color-scheme) or data-theme="dark";
   data-theme="light" forces light. */
:root {{
  color-scheme: light;
{palette(0)}
  --shadow-pop: 0 12px 32px rgba(20, 20, 24, 0.16), 0 0 0 1px rgba(20, 20, 24, 0.06);
{fonts}
{radii}
{spaces}
  --font: {FONT_STACK};
  --mono: {MONO_STACK};
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    color-scheme: dark;
{re.sub(r"^", "  ", palette(1), flags=re.M)}
    --shadow-pop: 0 16px 40px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.06);
  }}
}}
:root[data-theme="dark"] {{
  color-scheme: dark;
{palette(1)}
  --shadow-pop: 0 16px 40px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.06);
}}
"""


# Hard-coded styling in app code. Each pattern names what to use instead.
FORBIDDEN = [
    (re.compile(r"\.system\(size:"), "font size → AppTheme.font(...)"),
    (re.compile(r"(?<![A-Za-z])\.font\(\.(largeTitle|title2|title3|title|headline|subheadline|body|callout|footnote|caption2|caption)\b"),
     "system text style → AppTheme.font(...)"),
    (re.compile(r"cornerRadius: *[0-9]|\.cornerRadius\( *[0-9]"), "corner radius → AppTheme.Radius.*"),
    (re.compile(r"\.padding\((\.[a-zA-Z]+, *)?-?(?!0\))[0-9]"), "padding → AppTheme.Spacing.*"),
    (re.compile(r"spacing: *(?!0\b)[0-9]"), "spacing → AppTheme.Spacing.*"),
    (re.compile(r"Color\((red|white|hue):|Color\(nsColor: *\.system|Color\.accentColor|"
                r"\bColor\.(blue|red|green|orange|yellow|purple|pink|gray|mint|teal|indigo|cyan|brown)\b|"
                r"\.(foregroundColor|foregroundStyle|fill|tint)\(\.(blue|red|green|orange|yellow|purple|pink|gray|"
                r"mint|teal|indigo|cyan|brown|black|white)\)"), "color → AppTheme.*"),
    (re.compile(r"\.borderedProminent"), "prominent button → AppActionButton(kind: .primary)"),
]


def violations():
    found = []
    for folder, _dirs, files in os.walk(APP_DIR):
        if folder.startswith(THEME_DIR):
            continue
        for name in files:
            if not name.endswith(".swift"):
                continue
            path = os.path.join(folder, name)
            for number, line in enumerate(open(path, encoding="utf-8"), 1):
                if "design-exempt:" in line or line.lstrip().startswith("//"):
                    continue
                for pattern, fix in FORBIDDEN:
                    if pattern.search(line):
                        found.append(f"{os.path.relpath(path, ROOT)}:{number}: {fix}")
    return found


def email_violations(tokens):
    allowed = {light for _key, light, _dark in tokens["color"]}
    found = []
    for name in sorted(os.listdir(WEB_DIR)) if os.path.isdir(WEB_DIR) else []:
        if not (name.startswith("email") and name.endswith(".html")):
            continue
        text = open(os.path.join(WEB_DIR, name), encoding="utf-8").read()
        for value in sorted(set(v.upper() for v in re.findall(r"#[0-9A-Fa-f]{6}\b", text)) - allowed):
            found.append(f"design/web/{name}: {value} is not a light-palette token in docs/DESIGN.md")
    return found


def main():
    tokens = parse()
    generated = {SWIFT_OUT: swift(tokens), CSS_OUT: css(tokens)}
    if "--check" not in sys.argv:
        for path, content in generated.items():
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"wrote {os.path.relpath(path, ROOT)}")
        return
    problems = [f"{os.path.relpath(p, ROOT)} is stale: run make design-tokens"
                for p, c in generated.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != c]
    problems += violations() + email_violations(tokens)
    for problem in problems:
        print(problem)
    print(f"design-check: {len(problems)} problem(s)")
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
