#!/usr/bin/env python3
"""Generates the app's and the web's design tokens from the `tokens` block in docs/DESIGN.md, and checks that
nothing bypasses them.

  scripts/design-tokens.py          write DesignTokens.generated.swift, design/web/tokens.css and site/tokens.css
  scripts/design-tokens.py --check  fail if those files are stale, or if app code / email templates hard-code
                                    a color, font size, corner radius or spacing value
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESIGN = os.path.join(ROOT, "docs/DESIGN.md")
SWIFT_OUT = os.path.join(ROOT, "VoiceInk/DesignSystem/Theme/DesignTokens.generated.swift")
CSS_OUT = os.path.join(ROOT, "design/web/tokens.css")
SITE_CSS_OUT = os.path.join(ROOT, "site/tokens.css")  # the same file, so the site deploys on its own
APP_DIR = os.path.join(ROOT, "VoiceInk")
THEME_DIR = os.path.join(APP_DIR, "DesignSystem/Theme")
WEB_DIR = os.path.join(ROOT, "design/web")

FONT_STACK = ('-apple-system, BlinkMacSystemFont, "SF Pro Text", "PingFang SC", "Hiragino Sans GB", '
              '"Helvetica Neue", sans-serif')
MONO_STACK = 'ui-monospace, "SF Mono", SFMono-Regular, Menlo, monospace'


def parse():
    text = open(DESIGN, encoding="utf-8").read()
    block = re.search(r"```tokens\n(.*?)```", text, re.S).group(1)
    tokens = {"color": [], "font": [], "radius": [], "space": []}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, *values = line.split()
        group, key = name.split(".", 1)
        if group == "color":
            tokens[group].append((key, values[0].upper(), values[1].upper()))
        elif group == "font":
            tokens[group].append((key, int(values[0]), int(values[1])))
        else:
            tokens[group].append((key, int(values[0])))
    contrast = re.search(r"```contrast\n(.*?)```", text, re.S).group(1)
    tokens["contrast"] = {}
    for line in contrast.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            name, light, dark, *_ = line.split()
            tokens["contrast"][name.split(".", 1)[1]] = (light.upper(), dark.upper())
    return tokens


def contrast_ratio(a, b):
    def lum(hex_):
        channels = [int(hex_[i:i + 2], 16) / 255 for i in (1, 3, 5)]
        r, g, b_ = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
        return 0.2126 * r + 0.7152 * g + 0.0722 * b_
    hi, lo = sorted((lum(a), lum(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def contrast_problems(tokens):
    """Increase Contrast values: secondary text stays >= 4.5:1 on every background; borders stay 4.5:1 on cards."""
    colors = {key: (light, dark) for key, light, dark in tokens["color"]}
    hc = {key: colors.get(key) and tokens["contrast"].get(key, colors[key]) for key in colors}
    found = [f"contrast.{key} is not a color token" for key in tokens["contrast"] if key not in colors]
    for scheme, name in enumerate(("light", "dark")):
        backgrounds = [hc[k][scheme] for k in ("bg", "surface", "sunken", "accent-subtle")]
        for key in ("text-2", "text-3"):
            for background in backgrounds:
                if contrast_ratio(hc[key][scheme], background) < 4.5:
                    found.append(f"increased contrast {name}: {key} {hc[key][scheme]} on {background} is below 4.5:1")
        if contrast_ratio(hc["border"][scheme], hc["surface"][scheme]) < 4.5:
            found.append(f"increased contrast {name}: border on surface is below 4.5:1")
        if contrast_ratio(hc["text"][scheme], hc["accent-subtle"][scheme]) < 7:
            found.append(f"increased contrast {name}: text on accent-subtle is below 7:1")
    return found


def camel(key):
    head, *rest = re.split(r"[-.]", key)
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def swift_space_name(key):
    return "half" if key == "half" else f"x{key}"


def swift(tokens):
    out = [
        "// Generated by scripts/design-tokens.py from docs/DESIGN.md. Don't edit: change DESIGN.md and run",
        "// `make design-tokens`.",
        "import AppKit",
        "import SwiftUI",
        "",
        "enum DesignTokens {",
        "    /// Light and dark values switch with the window's appearance; colors with an HC pair also switch when macOS",
        "    /// Increase Contrast is on (docs/DESIGN.md, \"增强对比度\").",
        "    enum Palette {",
    ]
    for key, light, dark in tokens["color"]:
        more = ""
        if key in tokens["contrast"]:
            hc_light, hc_dark = tokens["contrast"][key]
            more = f", lightHC: 0x{hc_light[1:]}, darkHC: 0x{hc_dark[1:]}"
        out.append(f"        static let {camel(key)} = dynamic(light: 0x{light[1:]}, dark: 0x{dark[1:]}{more})")
    out += ["    }", "", "    /// App font sizes in points.", "    enum FontSize {"]
    for key, app, _web in tokens["font"]:
        out.append(f"        static let {camel(key)}: CGFloat = {app}")
    out += ["    }", "", "    enum Radius {"]
    for key, value in tokens["radius"]:
        out.append(f"        static let {camel(key)}: CGFloat = {value}")
    out += ["    }", "", "    enum Spacing {"]
    for key, value in tokens["space"]:
        out.append(f"        static let {swift_space_name(key)}: CGFloat = {value}")
    out += [
        "    }",
        "",
        "    /// ui-snapshots sets this to render the Increase Contrast look without touching the system setting.",
        "    static var forceIncreasedContrast = false",
        "",
        "    private static func dynamic(light: UInt32, dark: UInt32, lightHC: UInt32? = nil, darkHC: UInt32? = nil) -> Color {",
        "        Color(nsColor: NSColor(name: nil) { appearance in",
        "            let match = appearance.bestMatch(from: [",
        "                .accessibilityHighContrastDarkAqua, .accessibilityHighContrastAqua, .darkAqua, .vibrantDark, .aqua,",
        "                .vibrantLight,",
        "            ])",
        "            let isDark = match == .darkAqua || match == .vibrantDark || match == .accessibilityHighContrastDarkAqua",
        "            // SwiftUI doesn't always hand the provider a high-contrast appearance, so read the system setting too.",
        "            let increased = match == .accessibilityHighContrastDarkAqua || match == .accessibilityHighContrastAqua",
        "                || forceIncreasedContrast || NSWorkspace.shared.accessibilityDisplayShouldIncreaseContrast",
        "            let hex = increased ? (isDark ? (darkHC ?? dark) : (lightHC ?? light)) : (isDark ? dark : light)",
        "            return NSColor(",
        "                srgbRed: CGFloat((hex >> 16) & 0xFF) / 255, green: CGFloat((hex >> 8) & 0xFF) / 255,",
        "                blue: CGFloat(hex & 0xFF) / 255, alpha: 1)",
        "        })",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def css(tokens):
    def palette(index):
        return "\n".join(f"  --{key}: {values[index]};" for key, *values in tokens["color"])

    fonts = "\n".join(f"  --font-{key}: {web}px;" for key, _app, web in tokens["font"])
    radii = "\n".join(f"  --radius-{key}: {value}px;" for key, value in tokens["radius"])
    spaces = "\n".join(f"  --space-{key}: {value}px;" for key, value in tokens["space"])
    def more(index):
        return "\n".join(f"  --{key}: {values[index]};" for key, values in tokens["contrast"].items())

    return f"""/* Generated by scripts/design-tokens.py from docs/DESIGN.md. Don't edit: change DESIGN.md and run
   `make design-tokens`. Light by default, dark with the system (prefers-color-scheme) or data-theme="dark";
   data-theme="light" forces light. */
:root {{
  color-scheme: light;
{palette(0)}
  --shadow-pop: 0 12px 32px rgba(20, 20, 24, 0.16), 0 0 0 1px rgba(20, 20, 24, 0.06);
{fonts}
{radii}
{spaces}
  --font: {FONT_STACK};
  --mono: {MONO_STACK};
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    color-scheme: dark;
{re.sub(r"^", "  ", palette(1), flags=re.M)}
    --shadow-pop: 0 16px 40px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.06);
  }}
}}
:root[data-theme="dark"] {{
  color-scheme: dark;
{palette(1)}
  --shadow-pop: 0 16px 40px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.06);
}}
/* Increase Contrast (docs/DESIGN.md, "增强对比度"). */
@media (prefers-contrast: more) {{
  :root {{
{re.sub(r"^", "  ", more(0), flags=re.M)}
  }}
}}
@media (prefers-contrast: more) and (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{re.sub(r"^", "  ", more(1), flags=re.M)}
  }}
}}
@media (prefers-contrast: more) {{
  :root[data-theme="dark"] {{
{re.sub(r"^", "  ", more(1), flags=re.M)}
  }}
}}
"""


# Hard-coded styling in app code. Each pattern names what to use instead.
FORBIDDEN = [
    (re.compile(r"\.system\(size:"), "font size → AppTheme.font(...)"),
    (re.compile(r"(?<![A-Za-z])\.font\(\.(largeTitle|title2|title3|title|headline|subheadline|body|callout|footnote|caption2|caption)\b"),
     "system text style → AppTheme.font(...)"),
    (re.compile(r"cornerRadius: *[0-9]|\.cornerRadius\( *[0-9]"), "corner radius → AppTheme.Radius.*"),
    (re.compile(r"\.padding\((\.[a-zA-Z]+, *)?-?(?!0\))[0-9]"), "padding → AppTheme.Spacing.*"),
    (re.compile(r"spacing: *(?!0\b)[0-9]"), "spacing → AppTheme.Spacing.*"),
    (re.compile(r"Color\((red|white|hue):|Color\(nsColor: *\.system|Color\.accentColor|"
                r"\bColor\.(blue|red|green|orange|yellow|purple|pink|gray|mint|teal|indigo|cyan|brown)\b|"
                r"\.(foregroundColor|foregroundStyle|fill|tint)\(\.(blue|red|green|orange|yellow|purple|pink|gray|"
                r"mint|teal|indigo|cyan|brown|black|white)\)"), "color → AppTheme.*"),
    (re.compile(r"\.borderedProminent"), "prominent button → AppActionButton(kind: .primary)"),
]


def violations():
    found = []
    for folder, _dirs, files in os.walk(APP_DIR):
        if folder.startswith(THEME_DIR):
            continue
        for name in files:
            if not name.endswith(".swift"):
                continue
            path = os.path.join(folder, name)
            for number, line in enumerate(open(path, encoding="utf-8"), 1):
                if "design-exempt:" in line or line.lstrip().startswith("//"):
                    continue
                for pattern, fix in FORBIDDEN:
                    if pattern.search(line):
                        found.append(f"{os.path.relpath(path, ROOT)}:{number}: {fix}")
    return found


def email_violations(tokens):
    allowed = {light for _key, light, _dark in tokens["color"]}
    found = []
    for name in sorted(os.listdir(WEB_DIR)) if os.path.isdir(WEB_DIR) else []:
        if not (name.startswith("email") and name.endswith(".html")):
            continue
        text = open(os.path.join(WEB_DIR, name), encoding="utf-8").read()
        for value in sorted(set(v.upper() for v in re.findall(r"#[0-9A-Fa-f]{6}\b", text)) - allowed):
            found.append(f"design/web/{name}: {value} is not a light-palette token in docs/DESIGN.md")
    return found


# Web stylesheets use tokens.css variables only (the generated tokens.css files themselves are skipped).
WEB_CSS = [os.path.join(ROOT, "site/site.css"), os.path.join(WEB_DIR, "components.css")]


def css_violations():
    found = []
    for path in WEB_CSS:
        if not os.path.exists(path):
            continue
        for number, line in enumerate(open(path, encoding="utf-8"), 1):
            if re.search(r"#[0-9A-Fa-f]{3,8}\b", line):
                found.append(f"{os.path.relpath(path, ROOT)}:{number}: color → var(--…) from tokens.css")
    return found


def main():
    tokens = parse()
    generated = {SWIFT_OUT: swift(tokens), CSS_OUT: css(tokens), SITE_CSS_OUT: css(tokens)}
    if "--check" not in sys.argv:
        for path, content in generated.items():
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"wrote {os.path.relpath(path, ROOT)}")
        return
    problems = [f"{os.path.relpath(p, ROOT)} is stale: run make design-tokens"
                for p, c in generated.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != c]
    problems += contrast_problems(tokens)
    problems += violations() + email_violations(tokens) + css_violations()
    for problem in problems:
        print(problem)
    print(f"design-check: {len(problems)} problem(s)")
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
