#!/usr/bin/env python3
"""Renders docs/releases/*.md into site/changelog.html (newest first, English and 中文 in one page, switched by the
site's language toggle). Run it on every release and commit the result; see docs/release-checklist.md.

  scripts/site-changelog.py          write site/changelog.html
  scripts/site-changelog.py --check  fail if site/changelog.html is stale
"""
import glob
import hashlib
import html
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "site/changelog.html")
REPO = "https://github.com/Sma1lboy/yap"


def inline(text):
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    return re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', out)


def render(lines):
    """Markdown subset the release notes use: ## headings, - bullets, paragraphs. The h1, the "Changes since" line and the
    product blurb repeated in every file are dropped; the page header says it once."""
    out, items = [], []

    def flush():
        if items:
            out.append("<ul>" + "".join(f"<li>{inline(i)}</li>" for i in items) + "</ul>")
            items.clear()

    for line in lines:
        line = line.rstrip()
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            flush()
            out.append(f"<h3>{inline(line[3:])}</h3>")
        elif line.startswith("- "):
            items.append(line[2:])
        elif not line:
            flush()
        elif re.match(r"(Changes since|Yap is an open-source|1\.\d\.\d 之后的改动|Yap 是一个开源)", line):
            continue
        else:
            flush()
            out.append(f"<p>{inline(line)}</p>")
    flush()
    return "\n".join(out)


def releases():
    found = []
    for path in glob.glob(os.path.join(ROOT, "docs/releases/*.md")):
        version = os.path.basename(path)[:-3]
        text = open(path, encoding="utf-8").read()
        en, zh = re.split(r"^# Yap \S+（中文）\s*$", text, maxsplit=1, flags=re.M)
        found.append((tuple(int(n) for n in version.split(".")), version, en.splitlines(), zh.splitlines()))
    return sorted(found, reverse=True)


def page():
    articles = []
    for _, v, en, zh in releases():
        articles.append(f"""<article class="release" id="v{v}">
  <h2>Yap {v}</h2>
  <p class="fine"><a href="{REPO}/releases/tag/v{v}"><span lang="en">GitHub release</span><span lang="zh-Hans">GitHub 发布页</span></a></p>
  <div class="notes" lang="en">
{render(en)}
  </div>
  <div class="notes" lang="zh-Hans">
{render(zh)}
  </div>
</article>""")
    css = "".join(open(os.path.join(ROOT, "site", f), "rb").read().decode() for f in ("tokens.css", "site.css"))
    v = hashlib.md5(css.encode()).hexdigest()[:8]
    return TEMPLATE.replace("@@V@@", v).replace("@@ARTICLES@@", "\n".join(articles))


TEMPLATE = """<!doctype html>
<!-- Generated by scripts/site-changelog.py from docs/releases/*.md. Edit the notes, then rerun it. -->
<html lang="en" data-lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Yap changelog — every release</title>
<meta name="description" content="What changed in each Yap release, newest first.">
<meta name="color-scheme" content="light dark">
<link rel="canonical" href="https://yap.sma1lboy.me/changelog.html">
<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48">
<link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32.png">
<link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png">
<link rel="stylesheet" href="tokens.css?v=@@V@@">
<link rel="stylesheet" href="site.css?v=@@V@@">
</head>
<body>
<a class="skip" href="#main"><span lang="en">Skip to content</span><span lang="zh-Hans">跳到正文</span></a>
<header class="site-header">
  <div class="wrap">
    <a class="brand" href="./"><img src="assets/logo-96.png" alt="" width="28" height="28">Yap</a>
    <nav class="site-nav" aria-label="Pages">
      <a href="help.html"><span lang="en">Troubleshooting</span><span lang="zh-Hans">排障</span></a>
      <a href="changelog.html" aria-current="page"><span lang="en">Changelog</span><span lang="zh-Hans">更新日志</span></a>
    </nav>
    <div class="header-actions">
      <button class="btn btn--quiet" type="button" id="lang-toggle" aria-label="Switch language / 切换语言">中文</button>
    </div>
  </div>
</header>
<main id="main">
<section class="page">
  <div class="wrap">
    <p class="eyebrow"><span lang="en">Changelog</span><span lang="zh-Hans">更新日志</span></p>
    <h1><span lang="en">Every Yap release</span><span lang="zh-Hans">Yap 的每一个版本</span></h1>
    <p class="intro" lang="en">Newest first. Yap updates itself; <a href="https://github.com/Sma1lboy/yap/releases/latest/download/Yap.zip">the zip</a> and Homebrew always have the latest.</p>
    <p class="intro" lang="zh-Hans">最新的在最上面。Yap 会自己更新；<a href="https://github.com/Sma1lboy/yap/releases/latest/download/Yap.zip">zip</a> 和 Homebrew 装到的总是最新版。</p>
@@ARTICLES@@
  </div>
</section>
</main>
<footer class="site-footer">
  <div class="wrap">
    <p class="fine"><a href="./"><span lang="en">Home</span><span lang="zh-Hans">首页</span></a> · <a href="help.html"><span lang="en">Troubleshooting</span><span lang="zh-Hans">排障</span></a> · <a href="https://github.com/Sma1lboy/yap">GitHub</a></p>
  </div>
</footer>
<script src="lang.js"></script>
</body>
</html>
"""

if __name__ == "__main__":
    new = page()
    if "--check" in sys.argv:
        if not os.path.exists(OUT) or open(OUT, encoding="utf-8").read() != new:
            sys.exit("site/changelog.html is stale: run scripts/site-changelog.py")
    else:
        open(OUT, "w", encoding="utf-8").write(new)
